# Site settings
title: Not a Gnoshi...
description: "Some people call me Nots. I don't really care, but I'm not a Gnoshi!"
twitter_username: Notgnoshi
github_username:  Notgnoshi
email: "Notgnoshi@gmail.com"

# Build settings
markdown: kramdown
permalink: pretty
kramdown:
    input: GFM