# Site settings
title: Not a gnoshi...
description: "Test Description here"
baseurl: "http://notgnoshi.github.io"
url: "http://notgnoshi.github.io"
twitter_username: notgnoshi
github_username:  Notgnoshi
email: "notgnoshi@gmail.com"

# Build settings
markdown: kramdown
permalink: pretty
