# Site settings
title: notes from a nerd
description: An applied math student's thoughts on modern algebra, analysis, graph theory, general mathematics, Linux, numerical computation, and general computing.
twitter_username: Notgnoshi
github_username:  Notgnoshi
email: "Notgnoshi@gmail.com"

analytics:
    provider: google
    google:
        tracking_id: 'UA-63013145-1'
google_verify: zXtkKU9VeEySZsdlmhr1xyv_z6oYnjYyH-rmUTQI_SA

# Build settings
include: ['_pages']
permalink: /:title/
url: "https://notgnoshi.github.io"
baseurl: ""

markdown: kramdown
syntax-highlighting:
    enabled : true
kramdown:
    input: GFM

plugins:
    - jekyll-sitemap
