# Site settings
title: Not a gnoshi...
description: "Test Description here"
baseurl: ""
url: "http://notgnoshi.github.io"
twitter_username: notgnoshi
github_username:  Notgnoshi

# Build settings
markdown: kramdown
permalink: pretty
