# Site settings
title: notes from a nerd
description: "Simplicity is the final achievement. After one has played a vast quantity of notes and more notes, it is simplicity that emerges as the crowning reward of art. --Frederic Chopin"
twitter_username: Notgnoshi
github_username:  Notgnoshi
email: "Notgnoshi@gmail.com"

analytics:
    provider: google
    google:
        tracking_id: 'UA-63013145-1'

# Build settings
markdown: kramdown
syntax-highlighting:
    enabled : true
permalink: pretty
kramdown:
    input: GFM
safe: true
