# Site settings
title: Not a 'Gnoshi'...
description: "Some people call me 'Nots' others call me 'Hey you!'"
twitter_username: Notgnoshi
github_username:  Notgnoshi
email: "Notgnoshi@gmail.com"

# Build settings
markdown: kramdown
permalink: pretty
kramdown:
    input: GFM