# Site settings
title: Not a gnoshi...
description: "Test Description here"
twitter_username: Notgnoshi
github_username:  Notgnoshi
email: "Notgnoshi@gmail.com"

# Build settings
markdown: kramdown
permalink: pretty
